### ISSUE TITLE
question about Iowa dataset

### ISSUE THREAD

**Issue by SorourMo** [calebrob6/land-cover#10]
Hello,
Thank you for providing the code for your land cover classification algorithm and in particular, the ingenious super-resolution loss function. I have tried to downlead Iowa NDR 2009 land cover dataset with 1 m resolution. Unfortunately, I was not able to find any downloadable map/tif file. They only provide interactive webtools ([here](https://geodata.iowa.gov/maps/05c7740a09304883bdae3b3945966c1a/explore?layer=0&location=41.916221%2C-93.378650%2C8.00) and [here](https://programs.iowadnr.gov/geospatial/rest/services/LandCover/LC_2009_1m/MapServer)), which are not useful for measuring accuracy and miou. I was wondering if you had a link to download Iowa dataset.

Thanks,

**Comment by calebrob6** [comment]
Hi @SorourMo, the data is available for download in geotiff format by county here -- https://geodata.iowa.gov/pages/high-resolution-land-cover-in-2009-county-downloads.

Best,
Caleb
