### ISSUE TITLE
Potential error in color augmentation

### ISSUE THREAD

**Issue by chaitanya100100** [calebrob6/land-cover#8]
Hello @calebrob6 ,
Thanks for publishing your training code. I was going through your code and noticed something.

The color augmentation function assumes the array to be `num_channels x height x width` judging by the following line and the entire function code:
https://github.com/calebrob6/land-cover/blob/e38f4f353ebc6eb281a17449f5d9ce5289e397a4/landcover/datagen.py#L10-L12

But it is called here with the array sized `height x width x num_channels` here:
https://github.com/calebrob6/land-cover/blob/e38f4f353ebc6eb281a17449f5d9ce5289e397a4/landcover/datagen.py#L133-L137

Is it really an error or did I miss something?

**Comment by calebrob6** [comment]
Hi @chaitanya100100, this looks like an error. @rodrigoalmeida94, is this something that you all ran into?

**Comment by rodrigoalmeida94** [comment]
Hi @chaitanya100100 we did not encounter problems with this, but what you're saying makes sense. Could be that this n_ch variable has no effect in the result? Honestly not entirely sure, it was some time ago.

**Comment by chaitanya100100** [comment]
n_ch variable will indeed affect the image.
The code will take array sized `height x width x num_channels` as input. Interpreting it as `num_channels x height x width`, it will perform contrast and brightness change along the first dimension. So in effect, it will change the 'brightness' / 'contrast' of each row of image separately - just that it's no longer a valid contrast/brightness change. Changing each row separately is unnatural augmentation, but considering the fact that the intensity of brightness/contrast change is merely 5%, it will roughly look like random noise addition which by itself is an image augmentation.

**Comment by rodrigoalmeida94** [comment]
@chaitanya100100 that makes a lot of sense! Completely missed this. It would be great if you could submit a PR with a fix.
